[gcp_service_account]
type = "service_account"
project_id = "radiant-oven-468510-f2"
private_key_id = "11c64d0de64d5bdc80903e6d9d01d64938b07477"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCoFbdV4R4GZsu8
kihYitYWuIpC5U/zzoLVbBLde8u6aJRSUBPWTJ8+Ohs8mfbQLOH11BbnbTinqFnR
IBfIrrVzh9HLTMaHpSTPTjJI/Lu3gsGW6faNqeQgWO3ZPCTUaYjj2MAhIg6KKI5M
Ss7K660hAm0KFPKxquMBxWzElUgFgy5UgAlUWfzX6G4bzBF0d/Byi0TlI40c+emK
GxpCQmYz2aXwkJX975J3dldQQMTuI1hITNaPoIwSMEaeqMsGkbA6UML0VT51OF+K
dq3uG4dsnkWsnvP+01FCJCZFmjwAh/El9pzieUMVB/z3JOg3Cl+2uaOxu0PaQdEi
dPdJcJ8FAgMBAAECggEAA+QgzuWmaXUxa+ehnyRzqVSoqrzJRDZ4fpKrwHcwXlve
bHtlwipwQ04FZGVCD/assnawTbeQaLKJMGytmvE5yndkoBq3u9soW345bsl0Wl62
DEAqpi6T1Ts0d7jLN3mhTXkD6vXGtWRpSuiDxLHTsQsagBxqXo+QsBv5v8v0PgsO
SIze0+MXHa6FSAwynJ9qkZOROP1epz9VVjar49/EPvAAzKuA1x+AeY+ibGs/cQHb
pr55EwFd2plyoK94k54xbKik1NdGFsfaxImWglXXxIPQftn+Jl9HvE/oL2iPYc4U
U6M9toefqLuOCuorLTtQANz2V8cqrcLop5VkOg/jzwKBgQDVswNMoIX61TvEo3gt
r6x++i9Z7QkaS5B/GAE7lTbi7gLegc6vrs9qJsb5LZpQV3l6NdXGLoNLFZs+fshg
7+d5rD6TLifDZ+IlovkGx82rzYgKqgR0G3D32GlMNOf2kpZ4U7Y7gXyY+SsHu95X
fURrFwoPBjyH3Er3xzwVy74QcwKBgQDJWz06kFntWcZ05bpl1oHXnNbY9gjnbDNn
/bp14iuUlwsMDPr1au/3ijvJVGX3Oy+7fgNXj7H9ae2bk7Jq+TQBtaDFFF5tAn2z
v+P0f+1+FODohtaDUFfI/OZGB+iq4/PBe0j0cUT2xGTT97e3GgnqlR4YjW4tbDCn
uKM+jneMpwKBgQCNcPPBFwo2sEXj69KSYpEIZi1LFuGMfvE/vbKrLiLq5mANx9r2
Wvy7pLjTmkRl4s/rfJBmoMiTvNRI8/9Kcd9CoCe2oLj+09ZR1OGAhGRzzxC5Bjj2
ZGdME/f10Zqqj/F56OZX0meWlGzPrKAIRkgvnUsyEI2l2r/f6gWx422EUwKBgE1r
JTmVMt5NfD6J7YcmWLn79adpwbapJYLATabxlOwGvxqdCwi9WxKENcSNDL9oJEwk
gUhzWW4kAlWlDh6PPm3B1dSwpjWnlYk9KHpjjX7CrE77ORM4GuiOREN82vqJtrkX
m89QlcGDdXkCb8KY4mMtfmrWRhx00qhKF4n/4PtVAoGBAMWNdWtGzXuIG8LZi+qe
dTz08eqHMNDSWZh2hhbjXbZvLtZlX1xYpcBSO023yXwOTgSyXuQIMG/Cisnl7V9w
OB9ZzsVP4JfI2QDDhFft+9Ivv21LyrYgUnzegDf2gjlGFu7zJnrEy7Rb33aUktB8
RaylmG+XfH8vDLQRxEAlWEgr
-----END PRIVATE KEY-----"""
client_email = "araba-997@radiant-oven-468510-f2.iam.gserviceaccount.com"
client_id = "108680090741587464951"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/araba-997%40radiant-oven-468510-f2.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
